name: config_varible

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  varible_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        env:
          getting: Hello
  

      - name: New app
        run: echo "$getting This is the new ${{vars.APP_NAME}} app on the enviroment ${{vars.ENVIRONMENT}}."
