name: config_variable

on:
  workflow_dispatch:

jobs:
  variablec_job:
    runs-on: ubuntu-latest

    # Job-level variable
    env:
      getting: Hello

    steps:
      - uses: actions/checkout@v4

      - name: New app
        run: |
          echo "$getting This is the new ${{vars.APP_NAME }} app in the environment ${{vars.ENVIRONMENT }}."
